{% set version = "7.0" %}

package:
  name: readline
  version: {{ version }}

source:
  url: ftp://ftp.gnu.org/gnu/readline/readline-{{ version }}.tar.gz
  fn: readline-{{ version }}.tar.gz
  sha256: 56ba6071b9462f980c5a72ab0023893b65ba6debb4eeb475d7a563dc65cafd43
  patches:
    - patches/readline70-001

build:
  skip: true  # [win]

requirements:
  build:
    - pkg-config
    - ncurses 5.9*
  run:
    - ncurses 5.9*

test:
  commands:
  {% set readline_libs = [
    'libreadline',
    'libhistory'
  ] %}
  {% for lib in readline_libs %}
    - test -f ${PREFIX}/lib/{{ lib }}.a
    - test -f ${PREFIX}/lib/{{ lib }}.so      # [linux]
    - test -f ${PREFIX}/lib/{{ lib }}.dylib   # [osx]
  {% endfor %}

about:
  home: https://cnswww.cns.cwru.edu/php/chet/readline/rltop.html
  license: GPL3
  summary: library for editing command lines as they are typed in

extra:
  recipe-maintainers:
    - croth1
    - jakirkham
    - jjhelmus
    - pelson
    - msarahan
