travis:
  secure:
    BINSTAR_TOKEN: XX4gkgCHsLVP7Fq/XYfAasbmqJWdy1AEpMC8ClrOLbJrzxYVx5ZkS6tOWYRfuf1rnAjfRXPsRWuWl6tOrvccIXEzm3PozTQRr/y3lcxzx6dHNO+3q5IMtE4212zXkqNdWg0vD1tD6o8JVXKDtsVB1iLEkmigFH5PIFgwRqZuOJyCpgHICCh+rCKOg67oDauYDkQwIEPPvcATWU7PfwoMGrn54mruCefYGu/4NIXxsvQYxvOHQ6dF9NZHlblo07hiBC8FggX6UdnlK/TYZlSuBkXBuBKrSiTE1WP07FBr7CDHE0TRV/4zMv3Ihy/GjVR4amTI9lGGTFnU+Akwipxh2688gwyUGfTkUx8UyH/sy3KER7yEvVpRR7JbKnW2BbA2mjrX+lQa/CH0+1qhddprpTc/U6Qr+4AQTi94yyiCT3smQtN5l9I2WsxvVKkEGQE0Yu9xBURuz8kxMwhhikYzufUW83xnW00DCdqDtYBzvWmXHqqZx5i5Ui3morF+tQcx1YkIeZJOLI/RbLWwGsZMWSZVbyMbZcx0SpL/RcBHM93iWYjCd6WXIXs03si7PpJicksaFRijReVRDreN9DwtxZ1O4dWkZBpjuAG/r2R070rboOCNW5vlGCwiD8zrdmgYt707pNI3Me2w0fuN/0ZIHYuzf0cGx/S46XxK3zjWd90=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
